language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - dev

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: "Build & Deploy"
      script: ./angular.sh
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_S3_BUCKET_NAME
        skip_cleanup: true
        region: $AWS_DEFAULT_REGION
        local_dir: Angular_UI/dist/angular-material-frontend-client
        on:
          branch: dev
    - # This is node running 
      script: ./node.sh
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $AWS_S3_NODE_BUCKET_NAME
        skip_cleanup: true
        region: $AWS_DEFAULT_REGION
        local_dir: Node_Services/dist
        on:
          branch: dev