language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - dev

jobs:
  include:
    - stage: angular
      script: ./angular.sh
      script: echo two
    - stage: node
      script: echo three