language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - dev

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - cd ./Angular_UI
  - npm install -g @angular/cli

install:
  - npm install
      
script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- ng build --prod

before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  region: $AWS_DEFAULT_REGION
  local_dir: dist
  on:
    branch: dev